changelog:
  exclude:
    labels:
      - changelog-ignore
    authors: [ ]
  categories:
    - title: Breaking Changes
      labels:
        - "breaking change"
    - title: New features
      labels:
        - "feature"
    - title: Improvements
      labels:
        - "enhancement"
    - title: Fixes
      labels:
        - "bug"
    - title: Fixes (extensibility)
      labels:
        - "extensibility"
    - title: Documentation
      labels:
        - "documentation"
    - title: Others
      labels:
        - "*"
