// <autogenerated />

using System;
using System.Linq;
using Microsoft.Extensions.FileSystemGlobbing;
using Microsoft.Extensions.FileSystemGlobbing.Abstractions;

#pragma warning disable

#nullable disable

// ReSharper disable once CheckNamespace
namespace Pathy;

public static class ChainablePathExtensions
{
    public static ChainablePath[] GlobFiles(this ChainablePath path, string globPattern)
    {
        Matcher matcher = new(StringComparison.OrdinalIgnoreCase);
        matcher.AddInclude(globPattern);

        return matcher
            .Execute(new DirectoryInfoWrapper(path.ToDirectoryInfo()))
            .Files
            .Select(file => ChainablePath.From(path / file.Path))
            .ToArray();
    }
}
